### ISSUE TITLE
add config option to enable / disable "dev mode" 

### ISSUE THREAD

**Issue by haniotak** [esnet/oscars#100]

**Comment by bmah888** [comment]
In particular, we want a way to (via config option) re-enable password authentication and user management so we can test them.  As it stands right now, neither feature is exposed.  It doesn't really matter what the default is as long as we can toggle this on or off as needed.

**Comment by bmah888** [comment]
As of 1.0beta1, local password authentication and user management work.  Should we just close this issue?

**Comment by bmah888** [comment]
Yes we should.  Closing.
