### ISSUE TITLE
generate commands for user hosts / network admins

### ISSUE THREAD

**Issue by haniotak** [esnet/oscars#101]
ifconfig statements, sample addressing, etc

**Comment by bmah888** [comment]
The idea here is that after a reservation gets provisioned, we want an easy way (perhaps via cut-and-paste) for an end-user (or system administrator) to plumb a VLAN interface onto the reservation, assign addresses, and do a simple connectivity check.  Being able to do this automatically would be even better, but complicated by the fact that some sort of authorization would be needed to run commands on end-hosts (digression:  this was at one point one of the use cases / goals for ENOS).
