### ISSUE TITLE
Can't set ingress bandwidth on node in new reservation

### ISSUE THREAD

**Issue by bmah888** [esnet/oscars#117]
Create a reservation with two nodes/junctions.

On either node, click "Use" on one fixture, then note that the ingress bandwidth field for the fixtures is 0.  Type a number into the ingress bandwidth field.  Tab to get off the field and see that it's a non-zero.  Then in the mini-map click on the other node.  Then in the mini-map click on this node to come back to it.  The ingress bandwidth for the fixture in question is still zero (although the "Use" checkbox is still checked).

Note that the pipe parameters for the link between the two nodes actually does retain the bandwidth field settings if you click off and come back to it.  This is more in line with expected behavior.

(As an aside, the use of the word "bandwidth" should strictly be "bitrate" or "throughput".)

**Comment by haniotak** [comment]
closing; does not apply to new version
