### ISSUE TITLE
My account page:  Password confirmation

### ISSUE THREAD

**Issue by bmah888** [esnet/oscars#123]
The "My Account" page offers the user a chance to change their password.  There is a single field for the new password.  There should probably be a confirmation password field as well, as is the case in many other applications, to guard against the user mis-typing their new password and locking themselves out of their account.  This is especially needed because the password characters are always obscured.

**Comment by bmah888** [comment]
(Ditto for the dialog for creating a new user.)

**Comment by haniotak** [comment]
moved issue to frontend
