### ISSUE TITLE
response code 200 with a request that can't be filled

### ISSUE THREAD

**Issue by alexsim8595** [esnet/oscars#175]
When vlan is in conflict for hold request, the validity in response returns the following: "validity" : {
    "valid" : false,
    "message" : "vlan not available: netlab-mx960-rt2:netlab-mx960-rt2:xe-0/0/0.2100\nvlan not available: netlab-7750sr12-rt1:netlab-7750sr12-rt1:9/1/1.2100\nvlan not available: netlab-7750sr12-rt2:netlab-7750sr12-rt2:10/1/5.2100\n".
The web response code, however, is in 200. The connection itself is successful, but the request is failed... would it be possible to return some other code than 200?

**Comment by haniotak** [comment]
resolved in 1.0.7
