### ISSUE TITLE
Create a connection as "Scheduled" but after creation, build mode is "Manual"

### ISSUE THREAD

**Issue by bmah888** [esnet/oscars#179]
Create a reservation with the build mode as the default "Scheduled".

After the reservation is created, invoke Details for that reservation and see that the build mode is now "Manual", with the control "Set build mode to Scheduled" available.  Wait until the reservation start time, and the connection is not automatically built, it indeed needs to be built explicitly by a user.

Observed on oscars-backend 1.0.8.

**Comment by haniotak** [comment]
actually a frontend issue; closing this
