### ISSUE TITLE
NSI reservation request between same STP successful.

### ISSUE THREAD

**Issue by jmacauley** [esnet/oscars#198]
Was able to successfully reserve a connection on the same STP which should be rejected with a "00710 – NO_TRANSPORTPLANE_PATH_FOUND" error:

urn:ogf:network:netlab.es.net:2013::netlab-mx960-rt1:xe-11_2_0:+?vlan=2009
urn:ogf:network:netlab.es.net:2013::netlab-mx960-rt1:xe-11_2_0:+?vlan=2009

Also was able to reserve a connection on two different STP sharing the same root port:

urn:ogf:network:netlab.es.net:2013::netlab-mx960-rt1:xe-11_2_0:+?vlan=2009
urn:ogf:network:netlab.es.net:2013::netlab-mx960-rt1:xe-11_2_0:+?vlan=2010

Should be rejected with the same "00710 – NO_TRANSPORTPLANE_PATH_FOUND" error.

**Comment by haniotak** [comment]
disallowed in 1.0.10
