### ISSUE TITLE
NSI: OSCARS allows for creation of reservation with endTime in the past. 

### ISSUE THREAD

**Issue by jmacauley** [esnet/oscars#201]
Able to create a reservation with a scheduled endTime more than 3 hours in the past.

<connectionId>PT3J</connectionId>

This should be rejected as invalid with an error of "00101 - MISSING_PARAMETER" and endTime listed in the variable section.

**Comment by jmacauley** [comment]
Also able to create reservation with endTime before startTime.

**Comment by haniotak** [comment]
now following validation path and will correctly reject the reservation but with a generic error message. need to improve error handling with the variables and all that in a later release.
