### ISSUE TITLE
Permit access to OSCARS 1.0 via https://oscars.es.net/

### ISSUE THREAD

**Issue by bmah888** [esnet/oscars#213]
The idea here is to make it possible to access the OSCARS 1.0 installation via the URL https://oscars.es.net/ in the same way that we access OSCARS 0.6 today.

Start work on this only after we're reasonably sure that OSCARS 1.0 is stable and we won't be rolling anything back.  While it's initially marked as a 1.0 release milestone, it really has to happen after the release/deployment.

**Comment by bmah888** [comment]
Keep this ticket open for outstanding decom work.

**Comment by bmah888** [comment]
ESNET-TASK0023284

**Comment by haniotak** [comment]
oscars-west has been decommissioned, I think we can close this?

**Comment by bmah888** [comment]
We should keep it open, it's waiting on ticket ESNET-TASK0023284, which is more decom-related work.

**Comment by bmah888** [comment]
ESNET-TASK0023284 completed and closed.
