### ISSUE TITLE
create public maven repositories

### ISSUE THREAD

**Issue by bmah888** [esnet/oscars#225]
It should be possible for someone to build OSCARS without having write access to ESnet's repositories on GitHub, or in fact without having any GitHub repositories at all.  The way it's built for RPMs today depends on being able to grab `oscars-frontend` files from a Maven repository in the `esnet/oscars-frontend` repository.

Ideally it should be possible to release tarballs that can be built standalone.  I don't think that would work right now.

**Comment by haniotak** [comment]
not necessary any more now that we have a monorepo
