### ISSUE TITLE
OSCARS port mapping issues across NSI interface.

### ISSUE THREAD

**Issue by jmacauley** [esnet/oscars#235]
It would appear that OSCARS NSA is changing the request STP when reservation is queried.
 
ConnectionId = d278b765-1085-4f62-b3ec-1d5a24d36fda

Requested destination port:
    ``urn:ogf:network:es.net:2013::wash-cr5:6_1_1:wix?vlan=3409``

was changed in the reservation query to:
    ``urn:ogf:network:es.net:2013::wash-cr5:6_1_1:+?vlan=3409``

SENSE is unable to map returned port to applicable parent point.

**Comment by haniotak** [comment]
resolved as of 1.0.22
