### ISSUE TITLE
[OS-7] add change-end-time operation 

### ISSUE THREAD

**Issue by haniotak** [esnet/oscars#240]
always succeeds if new end time is sooner than prev end time

**Comment by bmah888** [comment]
See also esnet/oscars-frontend#42.

**Comment by haniotak** [comment]
plan:
- new REST endpoint: /api/modify/eval/{$connectionId}


- add modify REST POST endpoint
- fields: connectionId, new end time.
- always succeeds if new end time < previous end time.
