### ISSUE TITLE
[OS-19] Replace SNMP collector API access with calls to Netbeam APIs

### ISSUE THREAD

**Issue by bmah888** [esnet/oscars#248]
OSCARS's topology update code uses data from one of the current SNMP collectors (`snmp-west1.es.net`), which is eventually destined to be turned down.  Work has been done to provide equivalent functionality via Netbeam APIs (not in final form as of this writing).  This issue is to track the work of code changes in OSCARS required to use those Netbeam APIs.

Because this work involves dependencies on other projects, it might not be possible to set a milestone for this issue yet.

**Comment by jdugan1024** [comment]
The current netbeam endpoints that should give you what you need are:

https://esnet-netbeam.appspot.com/api/network/esnet/prod/interfaces
https://esnet-netbeam.appspot.com/api/network/esnet/prod/saps

Can you take a look and see if that meets your needs?

Things that will change:

- The URL will move to an .es.net domain name
- The format of the data might change, but probably won't

Eventually this might move to gRPC but there will be some kind of HTTP/JSON based interface available. Either REST like now or possibly GraphQL (which is still HTTP/JSON).

If you need data that isn't represented there, please let me know and I'll work to get that fixed.

**Comment by sartaj10** [comment]
Done.
