### ISSUE TITLE
allow service MTU override through web ui

### ISSUE THREAD

**Issue by haniotak** [esnet/oscars#258]
- add UI component to select the connection MTU. Dropdown with options: 9000 (Jumbo) and 1500. Default is "9000"

- add field to Connection (and SimpleConnection) to record the MTU. Integer.
- add database field to connection table. 

- add PSS field for MTU to MxVPLS and AluVPLS classes under shared
- PSS field parameter values are: Connection MTU + 100 (for MX), +114 (ALU).

- add template variable for MTU to `build-mx-vpls-service.ftl, build-alu-vpls-service.ftl`

**Comment by sartaj10** [comment]
Fixed in v1.0.26
