### ISSUE TITLE
Feature Request: Make the Schedule start time optional

### ISSUE THREAD

**Issue by pwefel** [esnet/oscars#305]
In build mode = manual. Ignore the start timer. Allow the user to click the "build" control without having to wait for the timer to expire.

Thanks.

**Comment by haniotak** [comment]
this is somewhat more complicated because the start time is also the time at which the resource reservations start, so we shouldn't be able to let you build before the start time.

but, we will do something else where the default start time will be "ASAP"; so when you do click the "commit" button the start time will be set to the instant you clicked. and then you'll immediately be able to click "build".

**Comment by pwefel** [comment]
I obviously don't know the underlying mechanisms involved, but could you
set the start time to the time that the build button is pressed?

**Comment by haniotak** [comment]
No, it doesn't work like that.. what are you trying to achieve by wanting to change that particular timestamp? If you want to record when the build actually happened... we actually do keep that information in the database, it's not currently visible in the web UI though.

**Comment by pwefel** [comment]
My current understanding of the user interface is that the circuit won't be
built until the start timer expires. If I just want to change a fixture, I
have to dismantle the old circuit first and rebuild a new circuit. I can
create the new circuit in about 2 minutes, but then I have to wait 13
minutes for it to actually build. When I'm on the phone with say CERN,
coordinating the moves, I would like the circuit to build as soon as
possible. Especially if I have 6 circuits to change. What I currently do is
set the start time to 3 minutes and hope I get everything entered correctly
in time. Nothing like the pressure of a ticking clock to keep you
motivated!  :)   Hopefully I just have a misunderstanding of how to use the
UI.

Thanks,

-paul

**Comment by haniotak** [comment]
That's about as good as it gets right now. We will be pushing some changes that will help with that, though.

**Comment by haniotak** [comment]
This has been addressed in the latest version; default start time is now "ASAP".
