### ISSUE TITLE
duplicate loopback addresses are assigned on the network

### ISSUE THREAD

**Issue by dwcarder** [esnet/oscars#314]
> aparse -s nash-cr5 | grep 134.55.241.127
/configure router Base interface "lo0-JN74" address 134.55.241.127/32

> aparse -s wash-cr5 | grep 134.55.241.127
/configure router Base interface "lo0-KP2T" address 134.55.241.127/32

> aparse -s chic-cr5 | grep 134.55.241.128
/configure router Base interface "lo0-KP2T" address 134.55.241.128/32

> aparse -s eqx-ash-cr5 | grep 134.55.241.128
/configure router Base interface "lo0-JN74" address 134.55.241.128/32

**Comment by haniotak** [comment]
good news, I have found the root cause for these. I will be working on fixing ASAP

**Comment by haniotak** [comment]
Fixed with new PSS queue, fix deployed
