### ISSUE TITLE
Duplicate connection ID error text

### ISSUE THREAD

**Issue by bmah888** [esnet/oscars#36]
Due to the workflow/interaction between the Web UI front end, back end, and core application, this is unlikely to happen, however, if a connection request is made with an ID duplicating an existing connection, the result is a 409 status code with the text `Conflict for url: https://localhost:8000//resv/connection/add` (or something of that form).  It might be useful to have something more descriptive as the text, such as "Duplicated connection ID".

This is probably not terribly urgent, since in normal operation, the Web UI actually asks for a connection ID, but it could happen with a misbehaving API client.

```
hattori:oscars-newtech% core/src/test/python/make-circuit.py --id test4 --bitrate 1000000 --aport lbl-mr2:xe-0/2/0 --zport bnl-mr2:xe-2/0/0
Traceback (most recent call last):
  File "core/src/test/python/make-circuit.py", line 111, in <module>
    r.raise_for_status()
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://localhost:8000//resv/connection/add
```

**Comment by haniotak** [comment]
conflicts now have better error messages; still give out a 409 code but message does say "duplicate connection id". closing issue.
