### ISSUE TITLE
UI:  No "red" elements on reservation creation precheck failure

### ISSUE THREAD

**Issue by bmah888** [esnet/oscars#39]
If an absurdly large bandwidth reservation is attempted, the following message shows up in the Web UI:

`Precheck Failed: Cannot establish reservation with current parameters! Topology elements with insufficient bandwidth colored red.`

But there don't appear to be any nodes or links colored in red.

**Comment by bmah888** [comment]
(Found while doing some follow-up testing for #37.)

**Comment by bmah888** [comment]
Original report done with Firefox 52.0.1 (64-bit) on macOS Sierra.

Repeated on Safari Version 10.0.3 (12602.4.8) on macOS Sierra and Google Chrome Version 56.0.2924.87 (64-bit) on macOS Sierra with the same results.

**Comment by haniotak** [comment]
confirmed, basically the message is the same for every invocation of precheck even if say the reservation fails because of a different reason i.e. the wrong VLAN. precheck should return a list of What Went Wrong With This One & directions on how to resolve.
