### ISSUE TITLE
Show interface description in interface list

### ISSUE THREAD

**Issue by bmah888** [esnet/oscars#73]
From UI feedback session of 6 April 2017 (chin):

When selecting router ports for the endpoints of a new reservation, we should be able to see the interface description, maybe in the table of junction parameters (or whatever replaces it).

**Comment by bmah888** [comment]
It looks like we can see this as of 1.0beta3.  Should this issue be closed?

(Wish-list:  It'd be great if we could get the interface description as a hotlink anytime an interface is mentioned, but ultimately that's a nice-to-have feature.)

**Comment by haniotak** [comment]
closing (resolved) frontend  issue
