### ISSUE TITLE
Automatic topology updates

### ISSUE THREAD

**Issue by bmah888** [esnet/oscars#84]
OSCARS needs to automatically import new topology, from the ESDB topology service.

OSCARS 0.6 updated about once a day, but the new topology file is updated hourly (need to confirm this) so a more frequent import would be useful.

**Comment by bmah888** [comment]
Using the feature/esdb-topology branch to hold this work.

**Comment by bmah888** [comment]
The topology import script is just part of the solution.  OSCARS needs to know to poll the files at some interval and take the appropriate action with new versions of topology.

**Comment by bmah888** [comment]
This issue is now an epic, which encompasses the three (I think) parts of this work.

**Comment by haniotak** [comment]
This has been completed as of 1.0.13 - we have:
- a topology generation process that collects all info from ESDB and graphite,
- generates new topology files for OSCARS to use,
- a periodic task that checks for new files and imports any changes
