### ISSUE TITLE
Support explicit routing

### ISSUE THREAD

**Issue by bmah888** [esnet/oscars#88]
From UI feedback session of 6 April 2017 (ctracy):

There should be a way to explicitly control the routing of a connection, as is possible in OSCARS 0.6.

**Comment by JeremyPlante** [comment]
Is this just a UI recommendation or a service request? 1.0 supports explicit routing in three ways: full exact specification, partial waypoint specification, and blacklist avoidance specification.

**Comment by haniotak** [comment]
The UI elements are not quite there basically.

**Comment by bmah888** [comment]
This issue is basically esnet/oscars-frontend#43.  That issue is actually in the right repository, so close this one.
