### ISSUE TITLE
Process topology updates

### ISSUE THREAD

**Issue by bmah888** [esnet/oscars#92]
Part of automatic topology updates is having the concept that the topology *can* change at more or less arbitrary times.

It's not clear as of this writing whether or not that concept is supported by OSCARS 1.0 code as it currently exists.

(For example, if a router disappears from the topology because it's been decommissioned, what happens to old circuit data that used that router?  If links change what happens to existing circuits or history of circuits?)

**Comment by haniotak** [comment]
closing issue ; latest version supports topology change version tracking & merging
